In [1]:
import yfinance as yf

In [234]:
yf.download("^FTSE", interval="1d", start_date="2020-07-15", end_date="2020-07-18")

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
1984-01-03,997.500000,1001.400024,997.500000,997.500000,997.500000,0
1984-01-04,997.500000,999.500000,993.299988,998.599976,998.599976,0
1984-01-05,1007.099976,1015.799988,1007.099976,1015.799988,1015.799988,0
1984-01-06,1019.000000,1029.300049,1019.000000,1029.000000,1029.000000,0
1984-01-09,1030.599976,1035.400024,1030.599976,1034.599976,1034.599976,0
...,...,...,...,...,...,...
2020-07-13,6095.399902,6187.299805,6095.399902,6176.200195,6176.200195,614241100
2020-07-14,6176.200195,6179.799805,6093.200195,6179.799805,6179.799805,717546900
2020-07-15,6179.799805,6323.600098,6179.799805,6292.700195,6292.700195,747302000
2020-07-16,6292.700195,6296.799805,6227.299805,6250.700195,6250.700195,521796200
2020-07-17,6250.700195,6293.700195,6230.000000,6290.299805,6290.299805,687096800

---
### Microsoft

In [11]:
msft = yf.Ticker("MSFT")

In [12]:
hist = msft.history(period="max")
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1986-03-13,0.06,0.06,0.06,0.06,1031788800,0.0,0.0
1986-03-14,0.06,0.07,0.06,0.06,308160000,0.0,0.0
1986-03-17,0.06,0.07,0.06,0.07,133171200,0.0,0.0
1986-03-18,0.07,0.07,0.06,0.06,67766400,0.0,0.0
1986-03-19,0.06,0.06,0.06,0.06,47894400,0.0,0.0
...,...,...,...,...,...,...,...
2020-07-10,213.62,214.08,211.08,213.67,26177600,0.0,0.0
2020-07-13,214.48,215.80,206.50,207.07,38135600,0.0,0.0
2020-07-14,206.13,208.85,202.03,208.35,37591800,0.0,0.0
2020-07-15,209.56,211.33,205.03,208.04,32144500,0.0,0.0
2020-07-16,205.40,205.70,203.29,204.30,7666156,0.0,0.0

In [13]:
msft.get_balance_sheet()

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [44]:
# show financials
msft.financials

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [45]:
msft.earnings

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [22]:
msft.get_institutional_holders(start="2018-07-01")

,Holder,Shares,Date Reported,% Out,Value
0,"Vanguard Group, Inc. (The)",640172572,2020-03-30,0.0844,100961616330
1,Blackrock Inc.,517578906,2020-03-30,0.0683,81627369265
2,State Street Corporation,314771248,2020-03-30,0.0415,49642573522
3,"FMR, LLC",237892832,2020-03-30,0.0314,37518078534
4,Price (T.Rowe) Associates Inc,172056401,2020-03-30,0.0227,27135015001
5,Capital World Investors,139116236,2020-03-30,0.0183,21940021579
6,"Geode Capital Management, LLC",115684966,2020-03-30,0.0153,18244675987
7,Capital International Investors,103523946,2020-03-30,0.0137,16326761523
8,Capital Research Global Investors,93247848,2020-03-30,0.0123,14706118108
9,Northern Trust Corporation,92119080,2020-03-30,0.0121,14528100106

In [28]:
# show balance heet
msft.balance_sheet
msft.quarterly_balance_sheet

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [15]:
msft.recommendations

                               Firm       To Grade From Grade Action
Date
2012-03-16 08:19:00  Argus Research            Buy                up
2012-03-19 14:00:00  Hilliard Lyons  Long-Term Buy              main
2012-03-22 07:03:00  Morgan Stanley     Overweight              main
2012-04-03 11:53:00             UBS            Buy              main
2012-04-20 06:18:00   Deutsche Bank            Buy              main
...                             ...            ...        ...    ...
2020-05-18 13:45:46     RBC Capital     Outperform              reit
2020-06-24 13:30:12  Argus Research            Buy              main
2020-06-24 13:58:07   Goldman Sachs            Buy              main
2020-07-09 10:31:04         Wedbush     Outperform              main
2020-07-09 12:39:10  Morgan Stanley     Overweight              main

[274 rows x 4 columns]

In [23]:
# show next event (earnings, etc)
msft.calendar

                                Value
Earnings Date     2020-07-22 00:00:00
Earnings Average                 1.38
Earnings Low                     1.28
Earnings High                    1.51
Revenue Average           36491800000
Revenue Low               36053000000
Revenue High              37098000000

In [19]:
pd.DataFrame([msft.info])

,zip,sector,fullTimeEmployees,longBusinessSummary,city,phone,state,country,companyOfficers,website,maxAge,address1,fax,industry,previousClose,regularMarketOpen,twoHundredDayAverage,trailingAnnualDividendYield,payoutRatio,volume24Hr,regularMarketDayHigh,navPrice,averageDailyVolume10Day,totalAssets,regularMarketPreviousClose,fiftyDayAverage,trailingAnnualDividendRate,open,toCurrency,averageVolume10days,expireDate,yield,algorithm,dividendRate,exDividendDate,beta,circulatingSupply,startDate,regularMarketDayLow,priceHint,currency,trailingPE,regularMarketVolume,lastMarket,maxSupply,openInterest,marketCap,volumeAllCurrencies,strikePrice,averageVolume,priceToSalesTrailing12Months,dayLow,ask,ytdReturn,askSize,volume,fiftyTwoWeekHigh,forwardPE,fromCurrency,fiveYearAvgDividendYield,fiftyTwoWeekLow,bid,tradeable,dividendYield,bidSize,dayHigh,exchange,shortName,longName,exchangeTimezoneName,exchangeTimezoneShortName,isEsgPopulated,gmtOffSetMilliseconds,quoteType,symbol,messageBoardId,market,annualHoldingsTurnover,enterpriseToRevenue,beta3Year,profitMargins,enterpriseToEbitda,52WeekChange,morningStarRiskRating,forwardEps,revenueQuarterlyGrowth,sharesOutstanding,fundInceptionDate,annualReportExpenseRatio,bookValue,sharesShort,sharesPercentSharesOut,fundFamily,lastFiscalYearEnd,heldPercentInstitutions,netIncomeToCommon,trailingEps,lastDividendValue,SandP52WeekChange,priceToBook,heldPercentInsiders,nextFiscalYearEnd,mostRecentQuarter,shortRatio,sharesShortPreviousMonthDate,floatShares,enterpriseValue,threeYearAverageReturn,lastSplitDate,lastSplitFactor,legalType,morningStarOverallRating,earningsQuarterlyGrowth,dateShortInterest,pegRatio,lastCapGain,shortPercentOfFloat,sharesShortPriorMonth,category,fiveYearAverageReturn,regularMarketPrice,logo_url
0,98052,Technology,144000,"Microsoft Corporation develops, licenses, and ...",Redmond,425-882-8080,WA,United States,[],http://www.microsoft.com,1,One Microsoft Way,425-706-7329,Software—Infrastructure,208.04,205.4,175.4846,0.009565,0.3233,None,205.7,None,33283687,None,208.04,196.57257,1.99,205.4,None,33283687,None,None,None,2.04,1597795200,0.933333,None,None,203.29,2,USD,34.03199,7673520,None,None,None,1548993429504,None,None,35742987,11.168022,203.29,204.19,None,800,7673520,216.38,32.786514,None,1.89,130.78,204.2,False,0.0098,1000,205.7,NMS,Microsoft Corporation,Microsoft Corporation,America/New_York,EDT,False,-14400000,EQUITY,MSFT,finmb_21835,us_market,None,10.988,None,0.33357,23.779,0.524996,None,6.23,None,7583439872,None,None,15.086,43132952,0.0057,None,1561852800,0.74093,46265999360,6.002,None,0.077276,13.539705,0.01425,1625011200,1585612800,1.24,1590710400,7472115344,1524041908224,None,1045526400,2:1,None,None,0.221,1593475200,2.47,None,0.0058,40829581,None,None,205.4,https://logo.clearbit.com/microsoft.com

In [50]:
pd.DataFrame([msft.info])

,zip,sector,fullTimeEmployees,longBusinessSummary,city,phone,state,country,companyOfficers,website,maxAge,address1,fax,industry,previousClose,regularMarketOpen,twoHundredDayAverage,trailingAnnualDividendYield,payoutRatio,volume24Hr,regularMarketDayHigh,navPrice,averageDailyVolume10Day,totalAssets,regularMarketPreviousClose,fiftyDayAverage,trailingAnnualDividendRate,open,toCurrency,averageVolume10days,expireDate,yield,algorithm,dividendRate,exDividendDate,beta,circulatingSupply,startDate,regularMarketDayLow,priceHint,currency,trailingPE,regularMarketVolume,lastMarket,maxSupply,openInterest,marketCap,volumeAllCurrencies,strikePrice,averageVolume,priceToSalesTrailing12Months,dayLow,ask,ytdReturn,askSize,volume,fiftyTwoWeekHigh,forwardPE,fromCurrency,fiveYearAvgDividendYield,fiftyTwoWeekLow,bid,tradeable,dividendYield,bidSize,dayHigh,exchange,shortName,longName,exchangeTimezoneName,exchangeTimezoneShortName,isEsgPopulated,gmtOffSetMilliseconds,quoteType,symbol,messageBoardId,market,annualHoldingsTurnover,enterpriseToRevenue,beta3Year,profitMargins,enterpriseToEbitda,52WeekChange,morningStarRiskRating,forwardEps,revenueQuarterlyGrowth,sharesOutstanding,fundInceptionDate,annualReportExpenseRatio,bookValue,sharesShort,sharesPercentSharesOut,fundFamily,lastFiscalYearEnd,heldPercentInstitutions,netIncomeToCommon,trailingEps,lastDividendValue,SandP52WeekChange,priceToBook,heldPercentInsiders,nextFiscalYearEnd,mostRecentQuarter,shortRatio,sharesShortPreviousMonthDate,floatShares,enterpriseValue,threeYearAverageReturn,lastSplitDate,lastSplitFactor,legalType,morningStarOverallRating,earningsQuarterlyGrowth,dateShortInterest,pegRatio,lastCapGain,shortPercentOfFloat,sharesShortPriorMonth,category,fiveYearAverageReturn,regularMarketPrice,logo_url
0,98052,Technology,144000,"Microsoft Corporation develops, licenses, and ...",Redmond,425-882-8080,WA,United States,[],http://www.microsoft.com,1,One Microsoft Way,425-706-7329,Software—Infrastructure,214.32,213.62,174.40102,0.009285,0.3233,None,214.08,None,31392385,None,214.32,194.7547,1.99,213.62,None,31392385,None,None,None,2.04,1597795200,0.933333,None,None,211.08,2,USD,35.5998,26177633,None,None,None,1620353613824,None,None,36184584,11.682519,211.08,214.1,None,2200,26177633,216.38,34.29695,None,1.89,130.78,214.25,False,0.0095,1000,214.08,NMS,Microsoft Corporation,Microsoft Corporation,America/New_York,EDT,False,-14400000,EQUITY,MSFT,finmb_21835,us_market,None,11.296,None,0.33357,24.446,0.538301,None,6.23,None,7583439872,None,None,15.086,42930465,0.0057,None,1561852800,0.74093,46265999360,6.002,None,0.056643,14.163463,0.01425,1625011200,1585612800,1.24,1589500800,7472115344,1566736646144,None,1045526400,2:1,None,None,0.221,1592179200,2.48,None,0.0057,44236712,None,None,213.62,https://logo.clearbit.com/microsoft.com

---
### TOYOTA

In [125]:
toyota = yf.Ticker("TM")

In [126]:
toyota.history(period="max")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2000-01-04,2732.84,2742.14,2621.30,2621.30,51900,0.0,0.0
2000-01-05,2742.14,2881.57,2677.07,2714.25,99900,0.0,0.0
2000-01-06,2742.14,2742.14,2658.48,2677.07,63500,0.0,0.0
2000-01-07,2686.37,2770.02,2677.07,2704.96,56000,0.0,0.0
2000-01-10,2704.96,2704.96,2704.96,2704.96,0,0.0,0.0
...,...,...,...,...,...,...,...
2020-07-13,2386.50,2468.00,2375.00,2461.50,3751100,0.0,0.0
2020-07-14,2427.50,2440.50,2408.50,2422.00,2064700,0.0,0.0
2020-07-15,2479.50,2494.50,2425.00,2445.00,2316100,0.0,0.0
2020-07-16,2500.00,2613.50,2500.00,2571.00,6433200,0.0,0.0
2020-07-17,2525.00,2549.00,2462.50,2477.50,3267300,0.0,0.0

In [58]:
toyota.get_balance_sheet()

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [59]:
toyota.balance_sheet

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [60]:
toyota.financials

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [127]:
toyota.get_institutional_holders()

,Holder,Shares,Date Reported,% Out,Value
0,Vanguard International Stock Index-Total Intl ...,1944180,2020-04-30,0.0056,4473558180
1,iShares MSCI EAFE Minimum Volatility ETF,1903100,2020-04-30,0.0055,4379033100
2,Vanguard Tax Managed Fund-Vanguard Developed M...,718631,2020-03-31,0.0021,1896467209
3,Old Westbury Large Cap Strategies Fund,457505,2020-04-30,0.0013,1052719005
4,iShares MSCI Eafe ETF,431600,2020-04-30,0.0012,993111600
5,iShares Core MSCI EAFE ETF,424800,2020-04-30,0.0012,977464800
6,Fidelity SAI International Low Volatility Inde...,394300,2020-04-30,0.0011,907284300
7,iShares MSCI Japan ETF,337700,2020-04-30,0.0010,777047700
8,iShares Edge MSCI Min Vol Global ETF,277200,2020-04-30,0.0008,637837200
9,Fidelity International Index Fund,224500,2020-04-30,0.0006,516574500

In [98]:
toyota.get_recommendations()

                                 Firm      To Grade    From Grade Action
Date
2012-02-17 06:15:00        Oxen Group          Hold                 init
2012-11-05 12:21:00     Credit Suisse    Outperform       Neutral     up
2013-01-10 16:25:47   Bank of America           Buy                   up
2013-01-15 10:42:09         Citigroup           Buy       Neutral     up
2013-02-07 14:39:56     Goldman Sachs           Buy       Neutral     up
2013-08-06 09:49:19   Mito Securities    Outperform       Neutral     up
2013-10-21 09:30:33          Barclays    Overweight                 init
2013-11-21 06:21:42         Jefferies          Hold                 init
2014-01-28 16:00:00               UBS           Buy                 init
2014-02-25 08:00:00         JP Morgan       Neutral                 init
2014-04-11 08:00:00            Mizuho           Buy       Neutral     up
2014-04-22 08:00:00    Mitsubishi UFJ       Neutral    Outperform   down
2014-06-16 16:37:01         ISI Group    Strong Buy                 init
2014-09-30 12:15:21         JP Morgan    Overweight       Neutral     up
2014-10-08 09:00:00         Jefferies           Buy                 main
2014-10-09 16:00:00   Bank of America           Buy       Neutral     up
2015-01-20 09:00:00         Jefferies           Buy                 main
2015-03-02 06:23:58         Jefferies          Hold           Buy   down
2015-04-07 06:54:43               UBS       Neutral           Buy   down
2015-06-04 09:00:00         Jefferies          Hold                 main
2015-07-15 17:25:48         Jefferies           Buy          Hold     up
2016-02-08 05:49:49  Societe Generale       Neutral           Buy   down
2016-05-13 12:46:21         Jefferies          Hold                 main
2016-05-27 11:14:26               UBS          Sell       Neutral   down
2016-08-25 04:38:59         Citigroup          Hold           Buy   down
2016-09-05 14:20:07     Goldman Sachs       Neutral           Buy   down
2017-07-11 14:02:30   Bank of America  Underperform       Neutral   down
2018-03-01 13:48:30   Bank of America       Neutral  Underperform     up
2018-06-04 12:42:33     Goldman Sachs           Buy       Neutral     up
2018-11-19 15:10:13         JP Morgan    Overweight       Neutral     up
2019-09-05 10:54:45    Morgan Stanley   Underweight  Equal-Weight   down
2020-03-31 09:16:01               UBS           Buy       Neutral     up

In [128]:
pd.DataFrame([toyota.info], index=pd.DatetimeIndex([datetime.date.today()]))

,zip,sector,longBusinessSummary,city,phone,country,companyOfficers,website,maxAge,address1,industry,address2,previousClose,regularMarketOpen,twoHundredDayAverage,trailingAnnualDividendYield,payoutRatio,volume24Hr,regularMarketDayHigh,navPrice,averageDailyVolume10Day,totalAssets,regularMarketPreviousClose,fiftyDayAverage,trailingAnnualDividendRate,open,toCurrency,averageVolume10days,expireDate,yield,algorithm,dividendRate,exDividendDate,beta,circulatingSupply,startDate,regularMarketDayLow,priceHint,currency,trailingPE,regularMarketVolume,lastMarket,maxSupply,openInterest,marketCap,volumeAllCurrencies,strikePrice,averageVolume,priceToSalesTrailing12Months,dayLow,ask,ytdReturn,askSize,volume,fiftyTwoWeekHigh,forwardPE,fromCurrency,fiveYearAvgDividendYield,fiftyTwoWeekLow,bid,tradeable,dividendYield,bidSize,dayHigh,exchange,shortName,longName,exchangeTimezoneName,exchangeTimezoneShortName,isEsgPopulated,gmtOffSetMilliseconds,quoteType,symbol,messageBoardId,market,annualHoldingsTurnover,enterpriseToRevenue,beta3Year,profitMargins,enterpriseToEbitda,52WeekChange,morningStarRiskRating,forwardEps,revenueQuarterlyGrowth,sharesOutstanding,fundInceptionDate,annualReportExpenseRatio,bookValue,sharesShort,sharesPercentSharesOut,fundFamily,lastFiscalYearEnd,heldPercentInstitutions,netIncomeToCommon,trailingEps,lastDividendValue,SandP52WeekChange,priceToBook,heldPercentInsiders,nextFiscalYearEnd,mostRecentQuarter,shortRatio,sharesShortPreviousMonthDate,floatShares,enterpriseValue,threeYearAverageReturn,lastSplitDate,lastSplitFactor,legalType,morningStarOverallRating,earningsQuarterlyGrowth,dateShortInterest,pegRatio,lastCapGain,shortPercentOfFloat,sharesShortPriorMonth,category,fiveYearAverageReturn,regularMarketPrice,logo_url
2020-07-18,105-7140,Industrials,"ANA Holdings Inc., together with its subsidiar...",Tokyo,81 3 6735 1001,Japan,[],http://www.ana.co.jp,1,Shiodome City Center,Airlines,"1-5-2, Higashi-Shimbashi Minato-ku",2571,2525,2821.5703,0.029172,0.2776,None,2549,None,3453925,None,2571,2567.3193,75,2525,None,3453925,None,None,None,75,1585526400,0.59593,None,None,2462.5,2,JPY,29.971811,3267300,None,None,None,829045866496,None,None,3729268,0.419937,2462.5,2484,None,0,3267300,3864,7.105572,None,1.69,2060,2477,False,0.0303,0,2549,JPX,ANA HOLDINGS INC,ANA Holdings Inc.,Asia/Tokyo,JST,False,32400000,EQUITY,9202.T,finmb_874001,jp_market,None,0.73,None,0.01401,5.99,-0.312188,None,None,None,334630016,None,None,3171.795,None,None,None,1585612800,0.23651,27655000064,82.661,None,0.080279,0.781103,0.06761,1648684800,1585612800,None,None,322988815,1440829538304,None,1506470400,1:10,None,None,None,None,None,None,None,None,None,None,2525,https://logo.clearbit.com/ana.co.jp

In [101]:
pd.DatetimeIndex([datetime.date.today()], name="hoge")

DatetimeIndex(['2020-07-18'], dtype='datetime64[ns]', name='hoge', freq=None)

---

In [129]:
# start<= day < end でダウンロード
data = yf.download(  # or pdr.get_data_yahoo(...
        # tickers list or string as well
        tickers = "OCDO.L",
        interval = "1m",
        start = "2020-07-14",
        end = "2020-07-16"
    )

[*********************100%***********************]  1 of 1 completed

In [130]:
data.head()

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2020-07-13 16:00:00+01:00,2032.900024,2032.900024,2031.00000,2031.00000,2031.00000,0
2020-07-13 16:01:00+01:00,2031.000000,2031.000000,2029.00000,2029.00000,2029.00000,5399
2020-07-13 16:02:00+01:00,2028.000000,2028.000000,2028.00000,2028.00000,2028.00000,3571
2020-07-13 16:03:00+01:00,2029.000000,2029.000000,2029.00000,2029.00000,2029.00000,2336
2020-07-13 16:04:00+01:00,2028.104980,2028.104980,2028.10498,2028.10498,2028.10498,1148

In [120]:
timezone = data.index.tz

In [121]:
data.index = data.index.tz_localize(None)

In [122]:
data.loc[data.index.date[0]:]

                      Open   High    Low  Close  Adj Close  Volume
Datetime
2020-07-14 10:11:00  2.100  2.100  2.100  2.100      2.100       0
2020-07-14 10:12:00  2.105  2.105  2.100  2.100      2.100   11497
2020-07-14 10:13:00  2.100  2.105  2.100  2.100      2.100   21511
2020-07-14 10:14:00  2.100  2.110  2.100  2.100      2.100   15506
2020-07-14 10:15:00  2.105  2.105  2.105  2.105      2.105     254
...                    ...    ...    ...    ...        ...     ...
2020-07-15 15:55:00  2.140  2.140  2.135  2.140      2.140  224174
2020-07-15 15:56:00  2.135  2.140  2.135  2.135      2.135  226254
2020-07-15 15:57:00  2.140  2.140  2.135  2.140      2.140  239412
2020-07-15 15:58:00  2.140  2.140  2.140  2.140      2.140    1818
2020-07-15 15:59:00  2.140  2.140  2.140  2.140      2.140       0

[570 rows x 6 columns]

In [82]:
data.index.tz_localize(timezone)

DatetimeIndex(['2020-07-14 09:00:00+09:00', '2020-07-14 09:01:00+09:00',
               '2020-07-14 09:02:00+09:00', '2020-07-14 09:03:00+09:00',
               '2020-07-14 09:04:00+09:00', '2020-07-14 09:05:00+09:00',
               '2020-07-14 09:06:00+09:00', '2020-07-14 09:07:00+09:00',
               '2020-07-14 09:08:00+09:00', '2020-07-14 09:11:00+09:00',
               ...
               '2020-07-15 14:50:00+09:00', '2020-07-15 14:51:00+09:00',
               '2020-07-15 14:52:00+09:00', '2020-07-15 14:53:00+09:00',
               '2020-07-15 14:54:00+09:00', '2020-07-15 14:55:00+09:00',
               '2020-07-15 14:56:00+09:00', '2020-07-15 14:57:00+09:00',
               '2020-07-15 14:58:00+09:00', '2020-07-15 14:59:00+09:00'],
              dtype='datetime64[ns, Asia/Seoul]', name='Datetime', length=713, freq=None)

---
### GOLD

In [131]:
gold = yf.Ticker("GC=F")

In [103]:
gold.info

{'previousClose': 1800.3,
 'regularMarketOpen': 1796.9,
 'twoHundredDayAverage': 1669.255,
 'trailingAnnualDividendYield': None,
 'payoutRatio': None,
 'volume24Hr': None,
 'regularMarketDayHigh': 1813.9,
 'navPrice': None,
 'averageDailyVolume10Day': 35855095,
 'totalAssets': None,
 'regularMarketPreviousClose': 1800.3,
 'fiftyDayAverage': 1762.721,
 'trailingAnnualDividendRate': None,
 'open': 1796.9,
 'toCurrency': None,
 'averageVolume10days': 35855095,
 'expireDate': 1598486400,
 'yield': None,
 'algorithm': None,
 'dividendRate': None,
 'exDividendDate': None,
 'beta': None,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 1795.2,
 'priceHint': 2,
 'currency': 'USD',
 'regularMarketVolume': 162684,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': 289325,
 'marketCap': None,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 30581009,
 'priceToSalesTrailing12Months': None,
 'dayLow': 1795.2,
 'ask': 1812.3,
 'ytdReturn': None,
 'askSize': 1200,
 'volume': 162684,
 'fiftyTwoWeekHigh': 1829.8,
 'forwardPE': None,
 'maxAge': 1,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': None,
 'fiftyTwoWeekLow': 1400.9,
 'bid': 1811.2,
 'tradeable': False,
 'dividendYield': None,
 'bidSize': 1400,
 'dayHigh': 1813.9,
 'exchange': 'CMX',
 'shortName': 'Gold Aug 20',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '-14400000',
 'underlyingSymbol': 'GCQ20.CMX',
 'quoteType': 'FUTURE',
 'symbol': 'GC=F',
 'underlyingExchangeSymbol': 'GCQ20.CMX',
 'headSymbol': 'GC=F',
 'market': 'us24_market',
 'regularMarketPrice': 1796.9,
 'logo_url': ''}

In [137]:
data = gold.history(
        start = "2020-07-03",
        end = "2020-07-03",
        interval="1d")

In [140]:
data.index.tz

---
### Tickers

In [245]:
data = yf.download(  # or pdr.get_data_yahoo(...
        # tickers list or string as well
        tickers = "^FTSE",
        start = "2020-07-01",
        end = "2020-07-03",
        interval="1d"
    )

[*********************100%***********************]  1 of 1 completed

In [246]:
data

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2020-06-30,6225.799805,6237.500000,6147.0,6169.700195,6169.700195,827284200
2020-07-01,6169.700195,6202.000000,6084.5,6158.000000,6158.000000,724502100
2020-07-02,6158.000000,6258.600098,6158.0,6240.399902,6240.399902,806189500

---
### FX

In [226]:
data = yf.download(  # or pdr.get_data_yahoo(...
        # tickers list or string as well
        tickers = "USDJPY=X EURUSD=X AUDUSD=X GBPUSD=X",
        start = "2020-07-10",
        end = "2020-07-13",
    )

[*********************100%***********************]  4 of 4 completed

1 Failed download:
- USDJPY=1: No data found, symbol may be delisted

In [227]:
data

           Adj Close                                  Close            \
            AUDUSD=X  EURUSD=X  GBPUSD=X USDJPY=1  AUDUSD=X  EURUSD=X
Date
2020-07-09  0.698910  1.133915  1.261352      NaN  0.698910  1.133915
2020-07-10  0.695894  1.128796  1.260509      NaN  0.695894  1.128796

                                   High                               \
            GBPUSD=X USDJPY=1  AUDUSD=X  EURUSD=X  GBPUSD=X USDJPY=1
Date
2020-07-09  1.261352      NaN  0.700202  1.137268  1.266945      NaN
2020-07-10  1.260509      NaN  0.696772  1.132477  1.266400      NaN

                 Low                                   Open            \
            AUDUSD=X  EURUSD=X  GBPUSD=X USDJPY=1  AUDUSD=X  EURUSD=X
Date
2020-07-09  0.695159  1.128796  1.260224      NaN  0.698529  1.133787
2020-07-10  0.692468  1.125720  1.256913      NaN  0.696282  1.128923

                                Volume
            GBPUSD=X USDJPY=1 AUDUSD=X EURUSD=X GBPUSD=X USDJPY=1
Date
2020-07-09  1.261273      NaN        0        0        0      NaN
2020-07-10  1.260653      NaN        0        0        0      NaN

---  
## Plyaground

In [13]:
yfTicker = yf.Ticker("KALU")

In [14]:
df = yfTicker.history(period="7d", interval="1m")

In [15]:
yfTicker.info

{'zip': '92610-2831',
 'sector': 'Basic Materials',
 'fullTimeEmployees': 2820,
 'longBusinessSummary': "Kaiser Aluminum Corporation manufactures and sells semi-fabricated specialty aluminum mill products. The company offers rolled, extruded, and drawn aluminum products used principally for aerospace and defense, automotive, consumer durables, electronics, electrical, and machinery and equipment applications. Its aerospace and high strength products include heat treat plates and sheets, hard alloy extruded shapes, cold finish rods and bars, seamless drawn tubes, and billets for aerospace and defense industries. The company's automotive extrusions include extruded aluminum products for structural components, crash management systems, anti-lock braking systems, and drawn tubes for drive shafts, as well as offers fabrication services, including sawing and cutting to length. Its general engineering products comprise alloy plate, sheet, rod, bar, tube, wire, and standard extrusion shapes used in various applications, including the production of military vehicles, ordnances, semiconductor manufacturing cells, electronic devices, after-market motor sport parts, tooling plates, parts for machinery and equipment, bolts, screws, nails, and rivets. The company also offers extruded, drawn, and cast billet aluminum products for industrial end uses. It sells its products directly to customers through sales personnel located in the United States, Canada, Western Europe, and China, as well as through independent sales agents in other regions of Asia, Latin America, and the Middle East. Kaiser Aluminum Corporation was founded in 1946 and is based in Foothill Ranch, California.",
 'city': 'Foothill Ranch',
 'phone': '949 614 1740',
 'state': 'CA',
 'country': 'United States',
 'companyOfficers': [],
 'website': 'http://www.kaiseraluminum.com',
 'maxAge': 1,
 'address1': '27422 Portola Parkway',
 'industry': 'Aluminum',
 'address2': 'Suite 200',
 'previousClose': 67.89,
 'regularMarketOpen': 67.96,
 'twoHundredDayAverage': 80.310356,
 'trailingAnnualDividendYield': 0.03844454,
 'payoutRatio': 0.6285,
 'volume24Hr': None,
 'regularMarketDayHigh': 68.27,
 'navPrice': None,
 'averageDailyVolume10Day': 152500,
 'totalAssets': None,
 'regularMarketPreviousClose': 67.89,
 'fiftyDayAverage': 72.31143,
 'trailingAnnualDividendRate': 2.61,
 'open': 67.96,
 'toCurrency': None,
 'averageVolume10days': 152500,
 'expireDate': None,
 'yield': None,
 'algorithm': None,
 'dividendRate': 2.68,
 'exDividendDate': 1595462400,
 'beta': 1.105322,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 65.58,
 'priceHint': 2,
 'currency': 'USD',
 'trailingPE': 28.347603,
 'regularMarketVolume': 124521,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': None,
 'marketCap': 1047083904,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 120688,
 'priceToSalesTrailing12Months': 0.7540572,
 'dayLow': 65.58,
 'ask': 66.07,
 'ytdReturn': None,
 'askSize': 1100,
 'volume': 124521,
 'fiftyTwoWeekHigh': 117.06,
 'forwardPE': 14.458516,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': 2.23,
 'fiftyTwoWeekLow': 54.54,
 'bid': 65.59,
 'tradeable': False,
 'dividendYield': 0.0395,
 'bidSize': 1000,
 'dayHigh': 68.27,
 'exchange': 'NMS',
 'shortName': 'Kaiser Aluminum Corporation',
 'longName': 'Kaiser Aluminum Corporation',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '-14400000',
 'quoteType': 'EQUITY',
 'symbol': 'KALU',
 'messageBoardId': 'finmb_319334',
 'market': 'us_market',
 'annualHoldingsTurnover': None,
 'enterpriseToRevenue': 0.88,
 'beta3Year': None,
 'profitMargins': 0.02686,
 'enterpriseToEbitda': 6.654,
 '52WeekChange': -0.3134266,
 'morningStarRiskRating': None,
 'forwardEps': 4.58,
 'revenueQuarterlyGrowth': None,
 'sharesOutstanding': 15812200,
 'fundInceptionDate': None,
 'annualReportExpenseRatio': None,
 'bookValue': 45.688,
 'sharesShort': 664591,
 'sharesPercentSharesOut': 0.0421,
 'fundFamily': None,
 'lastFiscalYearEnd': 1577750400,
 'heldPercentInstitutions': 1.0362,
 'netIncomeToCommon': 37300000,
 'trailingEps': 2.336,
 'lastDividendValue': None,
 'SandP52WeekChange': 0.0644362,
 'priceToBook': 1.4493959,
 'heldPercentInsiders': 0.020280002,
 'nextFiscalYearEnd': 1640908800,
 'mostRecentQuarter': 1593475200,
 'shortRatio': 5.88,
 'sharesShortPreviousMonthDate': 1590710400,
 'floatShares': 15427617,
 'enterpriseValue': 1221602048,
 'threeYearAverageReturn': None,
 'lastSplitDate': None,
 'lastSplitFactor': None,
 'legalType': None,
 'morningStarOverallRating': None,
 'earningsQuarterlyGrowth': None,
 'dateShortInterest': 1593475200,
 'pegRatio': 4.3,
 'lastCapGain': None,
 'shortPercentOfFloat': 0.0589,
 'sharesShortPriorMonth': 733251,
 'category': None,
 'fiveYearAverageReturn': None,
 'regularMarketPrice': 67.96,
 'logo_url': 'https://logo.clearbit.com/kaiseraluminum.com'}

In [204]:
timezone = df.index.tz  # timezone一時保存
df.index = df.index.tz_localize(None)

In [219]:
yfTicker.history(start="2020-07-17", end="2020-07-19", interval="1m").index

DatetimeIndex(['2020-07-16 16:06:00+01:00', '2020-07-16 16:07:00+01:00',
               '2020-07-16 16:08:00+01:00', '2020-07-16 16:09:00+01:00',
               '2020-07-16 16:10:00+01:00', '2020-07-16 16:11:00+01:00',
               '2020-07-16 16:12:00+01:00', '2020-07-16 16:13:00+01:00',
               '2020-07-16 16:14:00+01:00', '2020-07-16 16:15:00+01:00',
               ...
               '2020-07-17 16:20:00+01:00', '2020-07-17 16:21:00+01:00',
               '2020-07-17 16:22:00+01:00', '2020-07-17 16:23:00+01:00',
               '2020-07-17 16:24:00+01:00', '2020-07-17 16:25:00+01:00',
               '2020-07-17 16:26:00+01:00', '2020-07-17 16:27:00+01:00',
               '2020-07-17 16:28:00+01:00', '2020-07-17 16:29:00+01:00'],
              dtype='datetime64[ns, Europe/London]', name='Datetime', length=446, freq=None)